### ISSUE TITLE
community-in-clark-high-school.github.io/communityがcls.nyan-pro.com/にリダイレクトされて404エラーを吐く

### ISSUE THREAD

**Issue by PenguinCabinet** [Community-in-Clark-High-School/community#7]
2021/8/30 Now

https://community-in-clark-high-school.github.io/community/ に飛ぶと、 https://cls.nyan-pro.com/ にリダイレクトされて404エラーを吐く \
404エラーはおそらく、https://cls.nyan-pro.com/ のドメインが切れているからだろうけど、何故リダイレクトなのかが謎...

**Comment by Lv7Mapper** [comment]
なおった？

**Comment by Lv7Mapper** [comment]
cnameとaレコードの設定削除してないからかな
やっときます...

**Comment by PenguinCabinet** [comment]
お、直ってる

**Comment by PenguinCabinet** [comment]
@Lv7Mapper thanks
